global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using System;
global using System.IO;
global using System.Windows;
global using Test_InvoiceApp.Models;
global using Test_InvoiceApp.Extensions;
global using Test_InvoiceApp.DataContext;